// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jxjxgo.sso.domain.cache.session

object SessionProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Cg1zZXNzaW9uLnByb3RvIsICCgxTZXNzaW9uQ2FjaGUSFAoFdG9rZW4YASABKAlSBXRva2VuEhoKCGNsaWVudElkGAIgASgFU
  ghjbGllbnRJZBIYCgd2ZXJzaW9uGAMgASgJUgd2ZXJzaW9uEg4KAmlwGAQgASgDUgJpcBIeCgpkZXZpY2VUeXBlGAUgASgFUgpkZ
  XZpY2VUeXBlEiAKC2ZpbmdlclByaW50GAYgASgJUgtmaW5nZXJQcmludBIWCgZzdGF0dXMYByABKAVSBnN0YXR1cxIaCghtZW1iZ
  XJJZBgIIAEoA1IIbWVtYmVySWQSGgoIaWRlbnRpdHkYCSABKAlSCGlkZW50aXR5EiYKDmlkZW50aXR5VGlja2V0GAogASgJUg5pZ
  GVudGl0eVRpY2tldBIcCglnbXRDcmVhdGUYCyABKANSCWdtdENyZWF0ZUIjCiFjb20ubGF3c29mbmF0dXJlLnNzby5kb21haW4uY
  2FjaGViBnByb3RvMw=="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}