// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.lawsofnature.sso.domain.cache.session

object SessionProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
        """Cg1zZXNzaW9uLnByb3RvIqgCCgxTZXNzaW9uQ2FjaGUSFAoFdG9rZW4YASABKAlSBXRva2VuEhoKCGNsaWVudElkGAIgASgFU
  ghjbGllbnRJZBIOCgJpcBgDIAEoA1ICaXASHgoKZGV2aWNlVHlwZRgEIAEoBVIKZGV2aWNlVHlwZRIgCgtmaW5nZXJQcmludBgFI
  AEoCVILZmluZ2VyUHJpbnQSFgoGc3RhdHVzGAYgASgFUgZzdGF0dXMSGgoIbWVtYmVySWQYByABKANSCG1lbWJlcklkEhoKCGlkZ
  W50aXR5GAggASgJUghpZGVudGl0eRImCg5pZGVudGl0eVRpY2tldBgJIAEoCVIOaWRlbnRpdHlUaWNrZXQSHAoJZ210Q3JlYXRlG
  AogASgDUglnbXRDcmVhdGVCIwohY29tLmxhd3NvZm5hdHVyZS5zc28uZG9tYWluLmNhY2hlYgZwcm90bzM="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}